#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.url=jdbc:mysql://localhost:3306/tongxunlu?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#  # sql数据的初始化 2.5.0数据的初始化操作 改到了sql.init配置
#  #spring.sql.init.schema-locations=classpath*:sql/*.sql
#  #spring.sql.init.data-locations=classpath*:sql/data/*.sql
#
#  # 控制台打印sql
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#
#
#
#  # mybatis-plus配置
#mybatis-plus.mapper-locations=classpath:mapper/*.xml
#
##clssspath代表匹配一个文件
##clssspath*这个前缀代表匹配多个文件
#
#mybatis-plus:
#  # xml
#  mapper-locations: classpath:mapper/*Mapper.xml
#  # 实体扫描，多个package用逗号或者分号分隔
#  type-aliases-package: com.fengwenyi.mp3demo.model
#  configuration:
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
